<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="css/main.css">
</head>
<body>
    <section>
        <h1>Bons de commande</h1>

        <a href="index.php">Retourner à l'accueil</a>

        <!-- Etiquette avec fiche client -->
        <article class="order-form-customer">
            <h2><?= $customer['customerName'] ?></h2>
            <h3><?= $customer['contactFirstName'] ?> <?= $customer['contactLastName'] ?></h3>
            <p><?= $customer['addressLine1'] ?><?= $customer['addressLine2'] ?></p>
            <p></p>
            <p><?= $customer['city'] ?></p>
        </article>
        <hr>

        <!-- Le bon de commande -->
        <table class="standard-table">
            <caption>Bon de commande n° <?= $orderNumber ?></caption>
            <thead>
                <tr>
                    <th>Produit</th>
                    <th class="money-column">Prix Unitaire</th>
                    <th>Quantité</th>
                    <th class="money-column">Prix Total</th>
                </tr>
            </thead>
            <!-- Un footer de tableau HTML se positionne AVANT le body ! -->
           
            <tbody>
                <?php foreach ($orderDetails as $detail): ?>
                <tr>
                    <td><?= $detail['productName'] ?></td>
                    <td class="money-column"><?= number_format($detail['priceEach'], 2, ',', ' ') ?> €</td>
                    <td><?= $detail['quantityOrdered'] ?></td>
                    <td class="money-column"> <?= number_format($detail['totalPrice'], 2, ',', ' ') ?>€</td>
                </tr>
                <?php endforeach; ?>
            </tbody>

             <tfoot>
                <tr>
                    <th colspan="3">Montant Total HT</th>
                    <th><?= number_format($totalHT, 2, ',', ' ') ?>€</th>
                </tr>
                <tr>
                    <th colspan="3">TVA (20 %)</th>
                    <th><?= number_format($tvaAmount, 2, ',', ' ') ?>€</th>
                </tr>
                <tr>
                    <th colspan="3">Montant Total TTC</th>
                    <!-- Multiplier par 1.20 revient à ajouter 20% à une variable -->
                    <th><?= number_format($totalTTC, 2, ',', ' ') ?>€</th>
                </tr>
            </tfoot>
        </table>
    </section>
</body>
</html>